blank_issues_enabled: false
contact_links:
  - name: Project README
    url: https://github.com/JSunOfficial-arch/Self-Emergent-Self-Protection-Scanner-SESP-
    about: Check README for quick start and examples before filing an issue.
